name: movie_clean_architecture_modules
packages:
  - core/**
  - features/**

command:
  bootstrap:
    environment:
      sdk: ^3.8.1
      flutter: ">=1.17.0"


    dependencies:
     dio: ^5.8.0+1
     get_it: ^8.0.3
     injectable: ^2.5.0
     json_annotation: ^4.9.0

    dev_dependencies:
      json_serializable: ^6.9.5
      build_runner: ^2.5.3
      injectable_generator: ^2.7.0
      flutter_lints: ^5.0.0

scripts:
  cleanAndBootstrap: melos clean && melos bootstrap
  test: melos exec --concurrency=1 -- flutter test   #  the previous command is usede for test all tests in packages one by one
  update: flutter pub outdated
  upgrade: flutter pub upgrade --major-versions