import 'package:json_annotation/json_annotation.dart';

part 'movie_response.g.dart';

// This file was generated by json_serializable. To update it, run the following command:
// flutter pub run build_runner build
@JsonSerializable()
class MovieResponse {

  @JsonKey(name: "id")
  String? id;

  @JsonKey(name: "poster_path")
  String? posterPath;

  @JsonKey(name: "vote_average")
  String? voteAverage;

  @JsonKey(name: "original_title")
  String? originalTitle;

  @JsonKey(name: "overview")
  String? overview;

  @JsonKey(name: "release_date")
  String? releaseDate;

  @JsonKey(name: "title")
  String? title;

  MovieResponse(
    this.id,
    this.posterPath,
    this.voteAverage,
    this.originalTitle,
    this.title,
    this.overview,
    this.releaseDate,
  );

  // from json
  factory MovieResponse.fromJson(Map<String, dynamic> json) =>
      _$MovieResponseFromJson(json);

  // to json
  Map<String, dynamic> toJson() => _$MovieResponseToJson(this);
}
